version: '3.4'
services:
  mssql:
    image: microsoft/mssql-server-linux
    ports:
      - "1433:1433"
    environment:
      SA_PASSWORD: "CityHack2018"
      ACCEPT_EULA: "Y"
      MSSQL_PID: "Developer"
  cityhack:
    build: .
    depends_on: 
      - mssql
    ports:
      - "80:8080"
    entrypoint: ["wait-for-it", "mssql:1433", "--", "java", "-jar", "cityhack-backend.jar"]
    environment:
      SPRING_DATASOURCE_URL: "jdbc:sqlserver://mssql:1433"
      SPRING_DATASOURCE_USERNAME: "sa"
      SPRING_DATASOURCE_PASSWORD: "CityHack2018"
    volumes:
      - maven_cache:/root/.m2

volumes:
   maven_cache: